services:
  api-gateway:
    build: .
    container_name: api_gateway_dev
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload --forwarded-allow-ips="*"
    restart: unless-stopped